name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          pip install -e .[dev]
      - name: Lint
        run: |
          python -m pip install ruff
          ruff check src
      - name: Test
        run: |
          pytest -q
