name: Publish to PyPI
on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para hatch-vcs

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade build tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build hatchling hatch-vcs

      - name: Debug Git and Version Info
        run: |
          echo "Git tags:"
          git tag -l
          echo "Current commit:"
          git rev-parse HEAD
          echo "Git describe:"
          git describe --tags --always --dirty
          echo "GITHUB_REF: $GITHUB_REF"

      - name: Test version detection
        run: |
          python -c "
          import hatchling.metadata.core
          try:
              from hatch_vcs import VCSVersionSource
              print('hatch-vcs available')
          except ImportError as e:
              print(f'hatch-vcs not available: {e}')
          "

      - name: Build package
        run: |
          echo "Building package..."
          python -m build --verbose

      - name: Inspect built package
        run: |
          echo "Contents of dist/:"
          ls -la dist/
          echo "Checking metadata of wheel:"
          python -m zipfile -l dist/*.whl | head -20

      - name: Verify package metadata
        run: |
          pip install twine
          twine check dist/*

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@v1.10.1
        with:
          verify-metadata: false
          verbose: true
