name: Publish to PyPI

on:
  release:
    types: [published]      # corre al publicar un Release
  push:
    tags:
      - 'v*'                # corre al pushear tags tipo v0.1.0
  workflow_dispatch:         # botón manual "Run workflow"

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build twine hatchling

      - name: Build package
        run: python -m build

      - name: Publish to PyPI (API token)
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # skip-existing: true   # <- activa esto si vas a rehacer releases con la misma versión
